---
app: spring-postgres-example-12
auto_deploy: true
context: release-w9nh6s
domain: your-company-name.xyz
repo_name: dustyspace/spring-postgres
hostnames:
- backend: backend-spring-postgres-example-11-${env_id}.${domain}
environment_templates:
- name: ephemeral
- name: permanent
resources:
  cpu:
    limits: 1000m
    requests: 100m
  memory:
    limits: 1Gi
    requests: 100Mi
  replicas: 1
services:
- name: backend
  build:
    context: backend
  has_repo: true
  ports:
  - type: node_port
    target_port: '8080'
    port: '8080'
    loadbalancer: false
- name: db
  image: postgres
  has_repo: false
  volumes:
  - name: db-data
    type: persistent
    mount_path: "/var/lib/postgresql/data"
  storage:
    size: 10Gi
    type: aws-efs
  ports:
  - type: container_port
    port: '5432'
workflows:
- name: setup
  order_from:
  - step: services
    tasks:
    - services.db
    - services.backend
- name: patch
  order_from:
  - step: services
    tasks:
    - services.db
    - services.backend
- name: teardown
  parallelize:
  - step: remove_environment
    tasks:
    - release.remove_environment
